version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: power-platform-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
      - ./n8n/credentials:/home/node/.n8n/credentials
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-admin}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-n8n}
    depends_on:
      - postgres
      - redis
    networks:
      - power-platform-network

  postgres:
    image: postgres:13
    container_name: power-platform-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-n8n}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-n8n}
      - POSTGRES_DB=${POSTGRES_DB:-n8n}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - power-platform-network

  redis:
    image: redis:7-alpine
    container_name: power-platform-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - power-platform-network

  orchestrator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: power-platform-orchestrator
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ../src:/app/src
      - ../logs:/app/logs
    depends_on:
      - n8n
      - redis
    networks:
      - power-platform-network

volumes:
  n8n_data:
  postgres_data:
  redis_data:

networks:
  power-platform-network:
    driver: bridge